source 'http://review.pyyx.com/YueRen/iOS/Specs'
source 'https://github.com/MarkeJave/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
workspace 'YX'
project 'YXEDU/YXEDU.project'
#################################
target 'YXEDU' do 
 platform :ios, '8.0'
 pod 'MBProgressHUD'
 pod 'SSKeychain'
 pod 'CocoaLumberjack'
 pod 'Bugly'
 pod 'AFNetworking'
 pod 'SSKeychain'
 pod 'YYKit'
 pod 'IQKeyboardManager'
 pod 'YRUtils', '0.0.12'
 #pod 'YRNetwork', '~> 0.0.18'
 pod 'YRNetwork'
 pod 'HWWeakTimer'
 pod 'UICollectionViewLeftAlignedLayout'
 pod 'SVProgressHUD'
 pod 'ZipArchive'
 pod 'MJRefresh'
 pod 'WMPageController'
 pod 'VTMagic'
 pod 'TZImagePickerController'
 pod 'FMDB'
 pod 'MagicalRecord'
 pod 'MJExtension'
 #pod 'KeychainItemWrapper'
 project 'YXEDU/YXEDU.project'
end
